### ISSUE TITLE
Cannot work with output folder :(

### ISSUE THREAD

**Issue by lucienimmink** [djhouseknecht/rollup-plugin-version-injector#10]
My application creates multiple chunks but this plugin cannot work with multiple chunk output since it requires output.file :(

**Comment by lucienimmink** [comment]
2 different pull requests have been submitted for this issue:
https://github.com/djhouseknecht/rollup-plugin-version-injector/pull/11
https://github.com/djhouseknecht/rollup-plugin-version-injector/pull/12

**Comment by djhouseknecht** [comment]
Thanks for the feedback and PRs! I will try to take a look at those this week and get them merged and a release out.
