### ISSUE TITLE
Default file regexp leads to skipped entries

### ISSUE THREAD

**Issue by peacegiverman** [djhouseknecht/rollup-plugin-version-injector#2]
When rollup is set up to build multiple inputs and more than one input uses the version injector plugin, VI will fail to replace entries in some of the outputs (when default regex is used).

This happens because the default regex has a global flag. With the global flag set, `RegExp.prototype.test()` works iteratively and tries to search from its last index whenever it is called. From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test#Using_test_on_a_regex_with_the_global_flag):

>When a regex has the global flag set, test() will advance the lastIndex of the regex. (RegExp.prototype.exec() also advances the lastIndex property.)
>
>Further calls to test(str) will resume searching str starting from lastIndex. The lastIndex property will continue to increase each time test() returns true. 

To avoid this issue, I would recommend defaulting to a non-global regex, since it is only being tested once per file. E.g.: `/\.(js|html|css)$/`.

*Steps to reproduce:*

1. Create a js file with `let version = [VI]{date}[/VI]`.
2. Create a rollup.config.js with the following default export:
```js
    import versionInjector from 'rollup-plugin-version-injector';
    
    export default [{
        input: 'input.js',
        output: {
            file: 'dist/out1.js',
            format: 'iife',
            name: 'Foo',
        },
        plugins: [
            versionInjector({
                injectInComments: false,
                injectInTags: {
                    dateFormat: 'isoUtcDateTime'
                }
            })
        ]
    }, {
        input: 'input.js',
        output: {
            file: 'dist/out2.js',
            format: 'iife',
            name: 'Foo',
        },
        plugins: [
            versionInjector({
                injectInComments: false,
                injectInTags: {
                    dateFormat: 'isoUtcDateTime'
                }
            })
        ]
    }, {
        input: 'input.js',
        output: {
            file: 'dist/out3.js',
            format: 'iife',
            name: 'Foo',
        },
        plugins: [
            versionInjector({
                injectInComments: false,
                injectInTags: {
                    dateFormat: 'isoUtcDateTime'
                }
            })
        ]
    }];
```
3. Execute `rollup --config`. String replacement will fail in at least one of the files (for me it's usually the last one).

*Workaround:*

Set `fileRegexp: /\.(js|html|css)$/,` in the version injector plugin configuration.

**Comment by djhouseknecht** [comment]
@peacegiverman sorry I am just now seeing this. I didn't get a notification from github. I will take a look at this ASAP. Thank you for the detailed report!
