### ISSUE TITLE
Any way to use multi-line comment style instead of single-line with `injectInComments`?

### ISSUE THREAD

**Issue by MasterKale** [djhouseknecht/rollup-plugin-version-injector#22]
I'm migrating from Webpack to Rollup, and am looking to this plugin as a replacement for **webpack-auto-inject-version**. It seems, though, that this plugin can only inject comments as single-line (`//`) style comments. Is there a way to set up `injectInComments` to use multiline (`/* */`) style comments instead?

The reason I ask is because, in the past, an aggressive bundling config in a project using my library put everything on a single line, including the single-line version comment. As a result about half the bundled code failed to work... The fix was to set [`multiLineCommentType: true` on the Webpack version injector](https://github.com/radswiat/webpack-auto-inject-version#componentsinjectascomment) to inject the version comment as a multiline comment block instead.

**Comment by djhouseknecht** [comment]
@MasterKale that is a great idea for a new feature. I am out of town this weekend but can definitely take a look at adding that when I get back. I need to bump some dependencies and swap out my travis build for github actions too. I'll tackle all of those at the same time.

**Comment by djhouseknecht** [comment]
@MasterKale sorry for the delay. I got back in town and then turned around and left. Been playing catch up all week. I decided to just switch out the single line comments `//` for multiline `/* */` for all js files. I don't think this will be an issue and keep the config from becoming more bloated. 

PR: https://github.com/djhouseknecht/rollup-plugin-version-injector/pull/24

**Comment by MasterKale** [comment]
Thank you for the new release! Keep on fightin' the good fight 😄
